Repository doctrine/DoctrineORMModule, pull requests merged in 2021-12, with the labels that each got.

#693 Allow symfony/console ^6.0.0
  composer.json
Labels: Enhacement

#694 Added EntityBasedFormBuilder for annotation-based form creation
  composer.json
  phpstan.neon
  src/Form/Annotation/DoctrineAnnotationListener.php
  src/Form/Annotation/EntityBasedFormBuilder.php
  tests/Assets/Entity/FormEntity.php
  tests/Form/Annotation/DoctrineAnnotationListenerTest.php
  tests/Form/Annotation/EntityBasedFormBuilderTest.php
Labels: Enhacement

#697 Update upstream workflows
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  src/Paginator/Adapter/DoctrinePaginator.php
Labels: Enhacement

#698 Fixed deprecation on Serializable interface
  .github/workflows/continuous-integration.yml
  phpunit.xml.dist
  src/Collector/MappingCollector.php
Labels: Bug

#699 Updated upstream workflows
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: Enhacement

#700 Added docs for `EntityBasedFormBuilder`
  LICENSE.md
  docs/en/developer-tools.rst
  docs/en/forms.rst
  docs/en/index.rst
  docs/en/miscellaneous.rst
  docs/en/sidebar.rst
Labels: Documentation

#701 Drop support for PHP 7.3
  .github/workflows/continuous-integration.yml
  composer.json
Labels: Enhacement
