Repository doctrine/DoctrineORMModule, pull requests merged in 2021-11, with the labels that each got.

#677 Removed UPGRADE.md, see Github releases instead
  UPGRADE.md
Labels: Enhacement

#680 Remove PHP version config from `composer.json`
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  composer.json
  psalm-baseline.xml
  psalm.xml
Labels: Enhacement

#681 Use upstream workflows for coding standards and release-on-milestone-closed
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: Enhacement

#682 Add sidebar to documentation on website
  README.md
  docs/en/index.rst
  docs/en/sidebar.rst
Labels: Documentation

#679 Updated docs and readme to include installation notes for PHP 8
  README.md
  docs/en/index.rst
Labels: Documentation

#683 Update dependencies and allow PHP 8.1
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  ci/config/application.config.php
  composer.json
  psalm-baseline.xml
  psalm.xml
  tests/config.php
Labels: Enhacement

#685 Updated doctrine/coding-standard to 9.0
  .gitattributes
  .gitignore
  LICENSE
  composer.json
  phpcs.xml
  tests/Assets/Entity/Category.php
  tests/Assets/Entity/City.php
  tests/Assets/Entity/Country.php
  tests/Assets/Entity/Date.php
  tests/Assets/Entity/EntityWithoutRepository.php
  tests/Assets/Entity/FormEntity.php
  tests/Assets/Entity/FormEntityTarget.php
  tests/Assets/Entity/Issue237.php
  tests/Assets/Entity/Product.php
  tests/Assets/Entity/ResolveTarget.php
  tests/Assets/Entity/Target.php
  tests/Assets/Entity/TargetEntity.php
  tests/Assets/Entity/Test.php
  tests/Assets/Fixture/TestFixture.php
  tests/Assets/GraphEntity/Address.php
  tests/Assets/GraphEntity/Session.php
  tests/Assets/GraphEntity/User.php
  tests/Assets/GraphEntity/UserGroup.php
  tests/Assets/RepositoryClass.php
  tests/Assets/Types/MoneyType.php
  tests/CliConfiguratorTest.php
  tests/Collector/MappingCollectorTest.php
  tests/Collector/SQLLoggerCollectorTest.php
  tests/ConfigProviderTest.php
  tests/Framework/TestCase.php
  tests/Options/ConfigurationOptionsTest.php
  tests/Options/DBALConnectionTest.php
  tests/Options/DefaultRepositoryTest.php
  tests/Options/EntityManagerTest.php
  tests/Options/SQLLoggerCollectorOptionsTest.php
  tests/Paginator/AdapterTest.php
  tests/Service/ConfigurationFactoryTest.php
  tests/Service/DBALConnectionFactoryTest.php
  tests/Service/EntityResolverFactoryTest.php
  tests/Service/MigrationsCommandFactoryTest.php
  tests/Service/SQLLoggerCollectorFactoryTest.php
  tests/ServiceManagerFactory.php
  tests/Yuml/MetadataGrapherTest.php
  tests/Yuml/YumlControllerFactoryTest.php
  tests/Yuml/YumlControllerTest.php
  tests/config.php
  tests/testing.config.php
Labels: Enhacement

#686 Setup PHPStan and upgrade upstream workflows
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpstan.neon
  psalm.xml
  src/CliConfigurator.php
  src/Collector/MappingCollector.php
  src/Options/EntityManager.php
  src/Service/ConfigurationFactory.php
  src/Service/DBALConnectionFactory.php
  src/Service/DoctrineObjectHydratorFactory.php
  src/Service/EntityManagerFactory.php
  src/Service/EntityResolverFactory.php
  src/Service/MappingCollectorFactory.php
  src/Service/ObjectMultiCheckboxFactory.php
  src/Service/ObjectRadioFactory.php
  src/Service/ObjectSelectFactory.php
  src/Yuml/YumlController.php
  tests/Assets/Entity/FormEntity.php
  tests/Assets/GraphEntity/Address.php
  tests/Assets/Types/MoneyType.php
  tests/CliConfiguratorTest.php
  tests/Collector/MappingCollectorTest.php
  tests/Service/ConfigurationFactoryTest.php
  tests/Yuml/YumlControllerTest.php
Labels: Enhacement

#688 Updated composer scripts and removed coverage-checker
  .github/workflows/continuous-integration.yml
  build/.gitignore
  build/coverage-checker.php
  build/orm_other/.gitkeep
  composer.json
Labels: Enhacement

#687 Deprecate `createService()` methods as laminas-servicemanager 3.x is already required
  src/Service/CliConfiguratorFactory.php
  src/Service/ConfigurationFactory.php
  src/Service/DBALConfigurationFactory.php
  src/Service/DBALConnectionFactory.php
  src/Service/DoctrineObjectHydratorFactory.php
  src/Service/EntityManagerAliasCompatFactory.php
  src/Service/EntityManagerFactory.php
  src/Service/EntityResolverFactory.php
  src/Service/MappingCollectorFactory.php
  src/Service/MigrationsCommandFactory.php
  src/Service/ObjectMultiCheckboxFactory.php
  src/Service/ObjectRadioFactory.php
  src/Service/ObjectSelectFactory.php
  src/Service/ReservedWordsCommandFactory.php
  src/Service/RunSqlCommandFactory.php
  src/Service/SQLLoggerCollectorFactory.php
  src/Yuml/YumlControllerFactory.php
Labels: Enhacement

#690 Make static analysis more strict, Psalm level 5, PhpStan level 5
  phpstan.neon
  psalm.xml
  src/Options/DBALConnection.php
  src/Service/DBALConnectionFactory.php
  src/Service/EntityResolverFactory.php
  src/Yuml/MetadataGrapher.php
  src/Yuml/YumlControllerFactory.php
  tests/Assets/Entity/EntityWithoutRepository.php
  tests/Assets/Entity/TargetEntity.php
  tests/Framework/TestCase.php
Labels: Enhacement

#689 Add missing dependencies to composer.json to prevent unwanted soft dependencies
  composer.json
Labels: Bug

#691 [Docs] Update Configuration to use doctrine-dbal 3.0
  composer.json
  docs/en/configuration.rst
  docs/en/user-guide.rst
  phpstan.neon
Labels: Documentation
