Repository doctrine/DoctrineORMModule, pull requests merged in 2022-02, with the labels that each got.

#710 Require orm ^2.11 and adapt cache implementation
  composer.json
  src/Service/ConfigurationFactory.php
  tests/Service/ConfigurationFactoryTest.php
  tests/Service/DBALConnectionFactoryTest.php
Labels: Bug

#709 Add support for schema assets filter option
  docs/en/configuration.rst
  src/Options/Configuration.php
  src/Service/ConfigurationFactory.php
  tests/Service/ConfigurationFactoryTest.php
Labels: Enhacement

#713 Upgrade doctrine-laminas-hydrator to ^3.0
  composer.json
Labels: Enhacement

#714 Updated docs in regard of custom types and type comments
  .github/workflows/continuous-integration.yml
  docs/en/configuration.rst
  src/Options/DBALConnection.php
Labels: Documentation
